Fix PlaybackChannel forward declaration
This caused a jenkins build failure:

snd_worker.c:148: error: redefinition of typedef 'PlaybackChannel'
snd_worker.c:126: note: previous declaration of 'PlaybackChannel' was here